// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lending-system/ent/game"
	"lending-system/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameCreate is the builder for creating a Game entity.
type GameCreate struct {
	config
	mutation *GameMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (gc *GameCreate) SetName(s string) *GameCreate {
	gc.mutation.SetName(s)
	return gc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (gc *GameCreate) SetNillableName(s *string) *GameCreate {
	if s != nil {
		gc.SetName(*s)
	}
	return gc
}

// SetType sets the "type" field.
func (gc *GameCreate) SetType(s string) *GameCreate {
	gc.mutation.SetType(s)
	return gc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (gc *GameCreate) SetNillableType(s *string) *GameCreate {
	if s != nil {
		gc.SetType(*s)
	}
	return gc
}

// SetOu sets the "ou" field.
func (gc *GameCreate) SetOu(s string) *GameCreate {
	gc.mutation.SetOu(s)
	return gc
}

// SetNillableOu sets the "ou" field if the given value is not nil.
func (gc *GameCreate) SetNillableOu(s *string) *GameCreate {
	if s != nil {
		gc.SetOu(*s)
	}
	return gc
}

// SetCu sets the "cu" field.
func (gc *GameCreate) SetCu(s string) *GameCreate {
	gc.mutation.SetCu(s)
	return gc
}

// SetNillableCu sets the "cu" field if the given value is not nil.
func (gc *GameCreate) SetNillableCu(s *string) *GameCreate {
	if s != nil {
		gc.SetCu(*s)
	}
	return gc
}

// SetNotes sets the "notes" field.
func (gc *GameCreate) SetNotes(s string) *GameCreate {
	gc.mutation.SetNotes(s)
	return gc
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (gc *GameCreate) SetNillableNotes(s *string) *GameCreate {
	if s != nil {
		gc.SetNotes(*s)
	}
	return gc
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (gc *GameCreate) AddUserIDs(ids ...int) *GameCreate {
	gc.mutation.AddUserIDs(ids...)
	return gc
}

// AddUser adds the "user" edges to the User entity.
func (gc *GameCreate) AddUser(u ...*User) *GameCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gc.AddUserIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (gc *GameCreate) Mutation() *GameMutation {
	return gc.mutation
}

// Save creates the Game in the database.
func (gc *GameCreate) Save(ctx context.Context) (*Game, error) {
	gc.defaults()
	return withHooks(ctx, gc.sqlSave, gc.mutation, gc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gc *GameCreate) SaveX(ctx context.Context) *Game {
	v, err := gc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gc *GameCreate) Exec(ctx context.Context) error {
	_, err := gc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gc *GameCreate) ExecX(ctx context.Context) {
	if err := gc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gc *GameCreate) defaults() {
	if _, ok := gc.mutation.Name(); !ok {
		v := game.DefaultName
		gc.mutation.SetName(v)
	}
	if _, ok := gc.mutation.GetType(); !ok {
		v := game.DefaultType
		gc.mutation.SetType(v)
	}
	if _, ok := gc.mutation.Ou(); !ok {
		v := game.DefaultOu
		gc.mutation.SetOu(v)
	}
	if _, ok := gc.mutation.Cu(); !ok {
		v := game.DefaultCu
		gc.mutation.SetCu(v)
	}
	if _, ok := gc.mutation.Notes(); !ok {
		v := game.DefaultNotes
		gc.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gc *GameCreate) check() error {
	if _, ok := gc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Game.name"`)}
	}
	if _, ok := gc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Game.type"`)}
	}
	if _, ok := gc.mutation.Ou(); !ok {
		return &ValidationError{Name: "ou", err: errors.New(`ent: missing required field "Game.ou"`)}
	}
	if _, ok := gc.mutation.Cu(); !ok {
		return &ValidationError{Name: "cu", err: errors.New(`ent: missing required field "Game.cu"`)}
	}
	if _, ok := gc.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "Game.notes"`)}
	}
	return nil
}

func (gc *GameCreate) sqlSave(ctx context.Context) (*Game, error) {
	if err := gc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gc.mutation.id = &_node.ID
	gc.mutation.done = true
	return _node, nil
}

func (gc *GameCreate) createSpec() (*Game, *sqlgraph.CreateSpec) {
	var (
		_node = &Game{config: gc.config}
		_spec = sqlgraph.NewCreateSpec(game.Table, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	)
	if value, ok := gc.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := gc.mutation.GetType(); ok {
		_spec.SetField(game.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := gc.mutation.Ou(); ok {
		_spec.SetField(game.FieldOu, field.TypeString, value)
		_node.Ou = value
	}
	if value, ok := gc.mutation.Cu(); ok {
		_spec.SetField(game.FieldCu, field.TypeString, value)
		_node.Cu = value
	}
	if value, ok := gc.mutation.Notes(); ok {
		_spec.SetField(game.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if nodes := gc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GameCreateBulk is the builder for creating many Game entities in bulk.
type GameCreateBulk struct {
	config
	builders []*GameCreate
}

// Save creates the Game entities in the database.
func (gcb *GameCreateBulk) Save(ctx context.Context) ([]*Game, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gcb.builders))
	nodes := make([]*Game, len(gcb.builders))
	mutators := make([]Mutator, len(gcb.builders))
	for i := range gcb.builders {
		func(i int, root context.Context) {
			builder := gcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GameMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gcb *GameCreateBulk) SaveX(ctx context.Context) []*Game {
	v, err := gcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcb *GameCreateBulk) Exec(ctx context.Context) error {
	_, err := gcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcb *GameCreateBulk) ExecX(ctx context.Context) {
	if err := gcb.Exec(ctx); err != nil {
		panic(err)
	}
}
