// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"lending-system/ent/game"
	"lending-system/ent/predicate"
	"lending-system/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (gu *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	gu.mutation.Where(ps...)
	return gu
}

// SetName sets the "name" field.
func (gu *GameUpdate) SetName(s string) *GameUpdate {
	gu.mutation.SetName(s)
	return gu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (gu *GameUpdate) SetNillableName(s *string) *GameUpdate {
	if s != nil {
		gu.SetName(*s)
	}
	return gu
}

// SetType sets the "type" field.
func (gu *GameUpdate) SetType(s string) *GameUpdate {
	gu.mutation.SetType(s)
	return gu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (gu *GameUpdate) SetNillableType(s *string) *GameUpdate {
	if s != nil {
		gu.SetType(*s)
	}
	return gu
}

// SetOu sets the "ou" field.
func (gu *GameUpdate) SetOu(s string) *GameUpdate {
	gu.mutation.SetOu(s)
	return gu
}

// SetNillableOu sets the "ou" field if the given value is not nil.
func (gu *GameUpdate) SetNillableOu(s *string) *GameUpdate {
	if s != nil {
		gu.SetOu(*s)
	}
	return gu
}

// SetCu sets the "cu" field.
func (gu *GameUpdate) SetCu(s string) *GameUpdate {
	gu.mutation.SetCu(s)
	return gu
}

// SetNillableCu sets the "cu" field if the given value is not nil.
func (gu *GameUpdate) SetNillableCu(s *string) *GameUpdate {
	if s != nil {
		gu.SetCu(*s)
	}
	return gu
}

// SetNotes sets the "notes" field.
func (gu *GameUpdate) SetNotes(s string) *GameUpdate {
	gu.mutation.SetNotes(s)
	return gu
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (gu *GameUpdate) SetNillableNotes(s *string) *GameUpdate {
	if s != nil {
		gu.SetNotes(*s)
	}
	return gu
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (gu *GameUpdate) AddUserIDs(ids ...int) *GameUpdate {
	gu.mutation.AddUserIDs(ids...)
	return gu
}

// AddUser adds the "user" edges to the User entity.
func (gu *GameUpdate) AddUser(u ...*User) *GameUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gu.AddUserIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (gu *GameUpdate) Mutation() *GameMutation {
	return gu.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (gu *GameUpdate) ClearUser() *GameUpdate {
	gu.mutation.ClearUser()
	return gu
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (gu *GameUpdate) RemoveUserIDs(ids ...int) *GameUpdate {
	gu.mutation.RemoveUserIDs(ids...)
	return gu
}

// RemoveUser removes "user" edges to User entities.
func (gu *GameUpdate) RemoveUser(u ...*User) *GameUpdate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return gu.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (gu *GameUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, gu.sqlSave, gu.mutation, gu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (gu *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := gu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (gu *GameUpdate) Exec(ctx context.Context) error {
	_, err := gu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gu *GameUpdate) ExecX(ctx context.Context) {
	if err := gu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (gu *GameUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	if ps := gu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := gu.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
	}
	if value, ok := gu.mutation.GetType(); ok {
		_spec.SetField(game.FieldType, field.TypeString, value)
	}
	if value, ok := gu.mutation.Ou(); ok {
		_spec.SetField(game.FieldOu, field.TypeString, value)
	}
	if value, ok := gu.mutation.Cu(); ok {
		_spec.SetField(game.FieldCu, field.TypeString, value)
	}
	if value, ok := gu.mutation.Notes(); ok {
		_spec.SetField(game.FieldNotes, field.TypeString, value)
	}
	if gu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.RemovedUserIDs(); len(nodes) > 0 && !gu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := gu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, gu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	gu.mutation.done = true
	return n, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetName sets the "name" field.
func (guo *GameUpdateOne) SetName(s string) *GameUpdateOne {
	guo.mutation.SetName(s)
	return guo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (guo *GameUpdateOne) SetNillableName(s *string) *GameUpdateOne {
	if s != nil {
		guo.SetName(*s)
	}
	return guo
}

// SetType sets the "type" field.
func (guo *GameUpdateOne) SetType(s string) *GameUpdateOne {
	guo.mutation.SetType(s)
	return guo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (guo *GameUpdateOne) SetNillableType(s *string) *GameUpdateOne {
	if s != nil {
		guo.SetType(*s)
	}
	return guo
}

// SetOu sets the "ou" field.
func (guo *GameUpdateOne) SetOu(s string) *GameUpdateOne {
	guo.mutation.SetOu(s)
	return guo
}

// SetNillableOu sets the "ou" field if the given value is not nil.
func (guo *GameUpdateOne) SetNillableOu(s *string) *GameUpdateOne {
	if s != nil {
		guo.SetOu(*s)
	}
	return guo
}

// SetCu sets the "cu" field.
func (guo *GameUpdateOne) SetCu(s string) *GameUpdateOne {
	guo.mutation.SetCu(s)
	return guo
}

// SetNillableCu sets the "cu" field if the given value is not nil.
func (guo *GameUpdateOne) SetNillableCu(s *string) *GameUpdateOne {
	if s != nil {
		guo.SetCu(*s)
	}
	return guo
}

// SetNotes sets the "notes" field.
func (guo *GameUpdateOne) SetNotes(s string) *GameUpdateOne {
	guo.mutation.SetNotes(s)
	return guo
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (guo *GameUpdateOne) SetNillableNotes(s *string) *GameUpdateOne {
	if s != nil {
		guo.SetNotes(*s)
	}
	return guo
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (guo *GameUpdateOne) AddUserIDs(ids ...int) *GameUpdateOne {
	guo.mutation.AddUserIDs(ids...)
	return guo
}

// AddUser adds the "user" edges to the User entity.
func (guo *GameUpdateOne) AddUser(u ...*User) *GameUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return guo.AddUserIDs(ids...)
}

// Mutation returns the GameMutation object of the builder.
func (guo *GameUpdateOne) Mutation() *GameMutation {
	return guo.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (guo *GameUpdateOne) ClearUser() *GameUpdateOne {
	guo.mutation.ClearUser()
	return guo
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (guo *GameUpdateOne) RemoveUserIDs(ids ...int) *GameUpdateOne {
	guo.mutation.RemoveUserIDs(ids...)
	return guo
}

// RemoveUser removes "user" edges to User entities.
func (guo *GameUpdateOne) RemoveUser(u ...*User) *GameUpdateOne {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return guo.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the GameUpdate builder.
func (guo *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	guo.mutation.Where(ps...)
	return guo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (guo *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	guo.fields = append([]string{field}, fields...)
	return guo
}

// Save executes the query and returns the updated Game entity.
func (guo *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	return withHooks(ctx, guo.sqlSave, guo.mutation, guo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (guo *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := guo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (guo *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := guo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (guo *GameUpdateOne) ExecX(ctx context.Context) {
	if err := guo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (guo *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeInt))
	id, ok := guo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := guo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := guo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := guo.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
	}
	if value, ok := guo.mutation.GetType(); ok {
		_spec.SetField(game.FieldType, field.TypeString, value)
	}
	if value, ok := guo.mutation.Ou(); ok {
		_spec.SetField(game.FieldOu, field.TypeString, value)
	}
	if value, ok := guo.mutation.Cu(); ok {
		_spec.SetField(game.FieldCu, field.TypeString, value)
	}
	if value, ok := guo.mutation.Notes(); ok {
		_spec.SetField(game.FieldNotes, field.TypeString, value)
	}
	if guo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.RemovedUserIDs(); len(nodes) > 0 && !guo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := guo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   game.UserTable,
			Columns: game.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Game{config: guo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, guo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	guo.mutation.done = true
	return _node, nil
}
