// Code generated by ent, DO NOT EDIT.

package ent

import (
	"lending-system/ent/game"
	"lending-system/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescName is the schema descriptor for name field.
	gameDescName := gameFields[0].Descriptor()
	// game.DefaultName holds the default value on creation for the name field.
	game.DefaultName = gameDescName.Default.(string)
	// gameDescType is the schema descriptor for type field.
	gameDescType := gameFields[1].Descriptor()
	// game.DefaultType holds the default value on creation for the type field.
	game.DefaultType = gameDescType.Default.(string)
	// gameDescOu is the schema descriptor for ou field.
	gameDescOu := gameFields[2].Descriptor()
	// game.DefaultOu holds the default value on creation for the ou field.
	game.DefaultOu = gameDescOu.Default.(string)
	// gameDescCu is the schema descriptor for cu field.
	gameDescCu := gameFields[3].Descriptor()
	// game.DefaultCu holds the default value on creation for the cu field.
	game.DefaultCu = gameDescCu.Default.(string)
	// gameDescNotes is the schema descriptor for notes field.
	gameDescNotes := gameFields[4].Descriptor()
	// game.DefaultNotes holds the default value on creation for the notes field.
	game.DefaultNotes = gameDescNotes.Default.(string)
}
